<?php

define("APPLICATION", __DIR__ . DIRECTORY_SEPARATOR . "..");
define("APPLICATION_SRC", APPLICATION . DIRECTORY_SEPARATOR . "src");
define('APPLICATION_PATH', __DIR__ . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR);
